- name: Install all damn things
  hosts: localhost
    # vars:
    # TODO: Opensource ssh private keys
    # source_key: "./.ssh/id_rsa"
    # dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: Update Apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
  tasks:
    - name: Core tasks
      ansible.builtin.include_tasks:
        tasks/core-setup.yml
    # TODO: dotfiles
    #  name: Dotfiles
    #  ansible.builtin.include_tasks:
    #    tasks/dotfiles.yml
    - name: Productivity Tools
      ansible.builtin.include_tasks:
        tasks/productivity.yml
    - name: NodeJS
      ansible.builtin.include_tasks:
        tasks/node.yml
    - name: ZSH
      ansible.builtin.include_tasks:
        tasks/zsh.yml
    - name: PIP/NPM Packages
      ansible.builtin.include_tasks:
        tasks/packages.yml
    - name: Fonts
      ansible.builtin.include_tasks:
        tasks/nerd-fonts.yml
    - name: Git Setup
      ansible.builtin.include_tasks:
        tasks/git-setup.yml
