- name: Install all damn things
  hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: Update Apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
  tasks:
    - name: SSH
      ansible.builtin.include_tasks:
        tasks/ssh.yml
    - name: Git Setup
      ansible.builtin.include_tasks:
        tasks/git-setup.yml
    - name: Core tasks
      ansible.builtin.include_tasks:
        tasks/core-setup.yml
    - name: Productivity Tools
      ansible.builtin.include_tasks:
        tasks/productivity.yml
    - name: NodeJS
      ansible.builtin.include_tasks:
        tasks/node.yml
    - name: ZSH
      ansible.builtin.include_tasks:
        tasks/zsh.yml
    # TODO: Install nvim
    - name: PIP/NPM Packages
      ansible.builtin.include_tasks:
        tasks/packages.yml
    - name: Fonts
      ansible.builtin.include_tasks:
        tasks/nerd-fonts.yml
    - name: Dotfiles
      ansible.builtin.include_tasks:
        tasks/dotfiles.yml
