- name: Install System Packages (1)
  become: true
  ansible.builtin.apt:
    name: ["build-essential", "python3-pip", "jq"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages (2)
  become: true
  ansible.builtin.apt:
    name: ["picom", "curl", "htop", "i3", "i3lock-fancy", "pavucontrol", "xterm", "unzip"]
  tags:
    - install
    - core
