- name: Is LinuxMint
  changed_when: false
  ansible.builtin.command:
    lsb_release -is
  register: is_linuxmint

- name: Get LinuxMint LSB release
  changed_when: false
  when: is_linuxmint.stdout == "Linuxmint"
  ansible.builtin.shell: >
    set -o pipefail &&
    cat /etc/upstream-release/lsb-release |
    grep DISTRIB_CODENAME |
    tr -d DISTRIB_CODENAME=
  register: codename

- name: Get Uwuntu LSB release
  changed_when: false
  when: is_linuxmint.stdout != "Linuxmint"
  ansible.builtin.command:
    lsb_release -cs
  register: codename

- name: Set lsb_release fact
  ansible.builtin.set_fact:
    lsb_release: "{{ codename.stdout }}"
