- name: Install FNM
  ansible.builtin.shell: |
    set -o pipefail
    curl -o- https://raw.githubusercontent.com/Schniz/fnm/master/.ci/install.sh | \
    bash -s -- --install-dir "$HOME/.fnm" --skip-shell
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: $HOME/.fnm

- name: Install Node LTS
  changed_when: true
  ansible.builtin.shell:
    ~/.fnm/fnm install --lts
  args:
    executable: /bin/bash
