- name: Get Packer
  ansible.builtin.git:
    repo: "https://github.com/wbthomason/packer.nvim"
    dest: "~/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags: &tags_for_nvim ["install", "nvim"]

- name: Add NVIM PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    update_cache: true
    codename: "{{ lsb_release }}"
  tags: *tags_for_nvim

- name: Install NVIM
  become: true
  ansible.builtin.apt:
    name:
      - neovim
  tags: *tags_for_nvim

- name: Install NVIM plugins
  changed_when: true
  ansible.builtin.shell:
    nvim --headless -c "autocmd User PackerComplete quitall" -c "PackerSync"
  tags: *tags_for_nvim

- name: Install NVIM Mason deps
  changed_when: true
  ansible.builtin.shell: >
    $HOME/.fnm/fnm exec --using=default
    nvim --headless +"MasonInstall eslint_d prettierd stylua" +q
  tags: *tags_for_nvim
  args:
    executable: /bin/bash
