- name: Install ZSH
  ansible.builtin.apt:
    name: ['zsh']
  become: true
  tags: &tags_for_zsh_tasks ['install', 'productivity', 'dotfiles', 'zsh']

- name: Change shell to zsh
  changed_when: false
  ansible.builtin.shell:
    chsh -s $(which zsh)
  become: true
  tags: *tags_for_zsh_tasks

- name: Check that zsh stuff exists
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Download Oh-My-Zsh
  when: not oh_my_stats.stat.exists
  changed_when: not oh_my_stats.stat.exists
  become_user: astral
  ansible.builtin.get_url:
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/.oh-my-installer
    mode: "0744"
  tags: *tags_for_zsh_tasks

- name: Install Oh-My-Zsh
  when: not oh_my_stats.stat.exists
  changed_when: not oh_my_stats.stat.exists
  ansible.builtin.command:
    /tmp/.oh-my-installer
  become_user: astral
  tags: *tags_for_zsh_tasks

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions
  tags: *tags_for_zsh_tasks
